### PR TITLE
Replace `rc` dependency with `@pnpm/npm-conf`

### LINKED ISSUE #39: Consider ditching rc as its not being maintained
rc is outdated and have security issue, consider replacing it with some of your own code making the packet free from dependanies.

### PR DESCRIPTION
**Pull request by Kytech**
This PR replaces the rc package with pnpm's package that they use to resolve npm configuration information. As an added bonus, pnpm's package handles all npm environment variables, freeing this package from needing to check for environment variables itself, such as `npm_config_userconfig`

I also noticed that the `getRegistryUrl` function's usage information in the README did not match the exposed API, so I corrected the README to document the current parameter usage (usage remains unchanged by this PR, just figured I'd keep the docs up to date). Additionally, in index.js, I resorted to cloning the options object to avoid mutating the passed-in value. All tests passed when I ran the test suite against these changes on my machine. 

One important consideration to note is that `@pnpm/npm-conf` only supports node versions 12 and up. As such, this PR would be a breaking change since this package currently supports node versions as old as v6, which would probably warrant a bump in the major version number upon release. We could continue to support old node versions, such as v6, if we use an older version of the pnpm package, though it would no longer be receiving updates, removing one of the major benefits of switching dependencies. As such, I believe the best course of action is to release one final patch version of the current package, but with a pinned rc version dependency (due to the recent security snafu) for use in node versions prior to v12, then merge this change in and release as v5 for use in node 12+.

Closes #39

### CODE REVIEW

**Comment by rexxars** [comment]
Thanks Kyler!

I have released v4.2.2 which pins `rc`.

Then, I cherry-picked your commits (because I needed to fix a few merge conflicts after the 4.2.2 change), and bumped the minimum version requirement to node 14 (since 12 is out of LTS), and was planning on releasing it as v5.0.0 - but I'm seeing some odd behavior when running this in CI:

https://github.com/rexxars/registry-auth-token/runs/6920069190?check_suite_focus=true
https://github.com/rexxars/registry-auth-token/tree/v5-ci

It looks like the tests are failing on node 14 - but I am totally unable to replicate locally.
Do you have any idea what could be causing this?

**Comment by Kytech** [comment]
Not sure off the top of my head, but I'll try running the tests against node 14 locally to see if I can reproduce. I don't recall which node version I was working on locally when I wrote this.

**Comment by Kytech** [comment]
Just confirmed that the tests fail in node 14, but work in 16+. I must have used some sort of syntax that I thought was supported in node 12 and 14, but was actually not available until a newer version. This is what happens when I'm always switching node versions!

**Comment by Kytech** [comment]
I think I may have figured out the issue. The PNPM package is smart enough to read environment variables. When running `npm test` npm sets the `npm_config_*` environment variables before launching the test script; it has resolved configuration options right before starting tests into the `process.env` of the test script. Since environment variable values take precedence, it's sometimes causing values defined in the `.npmrc` files created during tests to be ignored in favor of what the environment variables hold. I think to avoid that, clearing any `npm_config_*` environment variables before each test should clear up the issue.

**Comment by Kytech** [comment]
Just pushed that fix and it looks like CI is passing on node 14+, so it should be good to go! Feel free to reach out if there's anything else regarding this PR and I'll get back to you as soon as I can. I'll be a bit less available next week, but I'll keep an eye on my GitHub notifications.

**Comment by Kytech** [comment]
I also bumped the Mocha version since global hook support wasn't added until v8 and the version in use was quite old. Since we're only supporting v14+, I figured now would be a fine time to bump the mocha version.

**Comment by rexxars** [comment]
Thanks again for figuring this out - great work!
I've upstreamed the changes into my v5 branch and released it as v5.0.1. Much appreciated!

**Pull request closed without merging**
